# Removed theme: jekyll-theme-cayman as requested
title: "Music Decade Classification"
description: "A systematic approach to building and optimizing a Deep Neural Network for music decade classification using the Million Song Dataset."
author: "Your Name"
logo: "/assets/images/logo.png"  # Will create this in implementation phase

# GitHub Pages specific settings
baseurl: "/music_decade_classification" # the subpath of your site, e.g. /blog
url: "https://mohitbhimrajka.github.io" # the base hostname & protocol
repository: "MohitBhimrajka/music_decade_classification"

# Enhanced GitHub integration
github:
  is_project_page: true
  repository_url: https://github.com/MohitBhimrajka/music_decade_classification
  repository_name: music_decade_classification

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Navigation structure
navigation:
  - title: Introduction
    url: "#introduction"
  - title: Data
    url: "#data"
  - title: EDA
    url: "#eda"
  - title: Baseline
    url: "#baseline"
  - title: Optimization
    url: "#optimization"
  - title: Results
    url: "#results"

# Enable GitHub Pages plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Additional settings
permalink: pretty

# Custom variables for our enhanced styling
custom_settings:
  enable_animations: true
  enable_dark_mode: true
  primary_color: "#4A56E2"
  secondary_color: "#FF6978"
  enable_progress_bar: true

# Optional: Explicitly include CSS (May depend on theme's handling)
# Defaults might be needed if theme doesn't automatically include assets/css/style.css
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"
# include: ["assets/css/style.css"] # May not be needed if theme auto-includes

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .github